timvideos/HDMI2USB-litex-firmware

platforms/atlys.py
There are two options;
* Using the proprietary Digilent Adept Utilities.
* Using the FOSS fpgalink tool.
To use Digilent Adept Utilities, add the following to your ./make.py command;
-Op programmer adept
To use FPGALink, add the following to your ./make.py command;
-Op programmer fpgalink
=> Adding support for programming with onboard USB JTAG.

firmware/lm32/ci.c
That was the actual reason USB streaming was not working for me! I was trying all sorts of combinations like "encoder 1 50" "encoder 0 100", fiddling with mplayer etc for almost an hour...
Actual format is "encoder <quality> <source>" instead of "encoder <source> <quality>"
=> Fix help message for encoder settings

platforms/atlys.py, platforms/opsis.py
Fixes NameError when undefined programmer is used. Instead should raise ValueError as coded. Sample incorrect error output previously: "NameError: name 'programmer' is not defined"
=> Fix bug with programmer in atlys & opsis platform files

scripts/README.md, scripts/setup-env.sh
Split up the scripts/README.md in to sections adding a bit more detail. Added missing step to make lm32-firmware.
Added test to scripts/setup-env.sh to test to see if /opt/Xilinx/14.7/ISE_DS/settings64.sh has previously been sourced and display error
=> Expand bootstrap README and add test for /opt/Xilinx/14.7/ISE_DS/settings64.sh

.travis.yml
Lets keep #timvideos for discussion and #hdmi2usb for automated messages.
=> travis: Only announce in the HDMI2USB channel.

Makefile, Makefile.all, Makefile.fx2, Makefile.lm32
As requested by @enjoy-digital
=> makefiles: Adding Makefile to quickly test all targets.

scripts/setup-env.sh
The prompt now looks like this;
```
(H2U) XXXX
```
But if you set any of board/target/prog you get
```
(H2U B=opsis) XXXX
(H2U T=base) XXXX
```
This improves on @shenki's work in https://github.com/timvideos/HDMI2USB-misoc-firmware/issues/137
=> scripts: More fancy prompt.

firmware/lm32/ci.c, firmware/lm32/edid.c, firmware/lm32/encoder.c, firmware/lm32/fx2.c, firmware/lm32/hdmi_in0.c, firmware/lm32/hdmi_in1.c, firmware/lm32/hdmi_out0.c, firmware/lm32/hdmi_out1.c, firmware/lm32/main.c, firmware/lm32/opsis_eeprom.c, firmware/lm32/pll.c, firmware/lm32/tofe_eeprom.c
Fixes #168.
This doesn't change the misoc BIOS however. Most people should never get to that prompt.
=> firmware/lm32: Make all strings end in \r\n rather then just \n.

firmware/lm32/ci.c
All the command interface is really verbose.
It's really annoying doing testing and typing `video_matrix connect input0 output0` a few dozen times.  There should be a better way.
Instead of an elaborate Cisco IOS-style shortcode system, this is a really simple one which just aliases many commands to 1-character versions.
So instead of `video_matrix connect input0 output0`, you can write `x c 0 0`.  The difference between `input0` and `output0` are inferred by the position of the argument, and the ports are unidirectional, so this is all implicit.
There are similar aliases added in the command interface, which are all documented in the help strings.
We don't have any `inputX` commands, only `outputX`, so the outputs get the `X` commands (eg: `output0 off` -> `0 off`).
I don't have an SDK …
=> Add aliases that are less verbose

.travis/run.sh, Makefile, scripts/download-prebuilt.sh
Add make target to download pre-built firmware and bash script to do it
#115
=> Download prebuilt

platforms/atlys.py
* JP5 is required to have a jumper otherwise Input 0 does *not* work.
=> platforms/atlys: Adding comment about JP5.

firmware/lm32/edid.c
* Macs looked washed out, this fixes
* Value in-line with two other monitors EDID data
Hi @mithro, this definitely fixes the issue - verified by changing this value a few times and comparing the Color Profiles on my Mac.  This value matches the EDID on two monitors I tested, and in my eyes looks about right.
=> Adjusts gamma value provided in in EDID

platforms/opsis.py
Otherwise the board will pull G22 low when programming.
=> platforms/opsis: Add pullup to G22.

scripts/bootstrap.sh, scripts/flash-hdmi2usb.sh, scripts/get-env-root.sh, scripts/get-env.sh, scripts/setup-env.sh, scripts/view-hdmi2usb.sh
* Fixes #238 - "Bootstrap script shouldn't do a `git pull`, should instead warn about existing checkout."
* Fixes #239 - "Bootstrap and other scripts should refuse to run as root"
=> Fixes issue #238 and #239

firmware/lm32/ci.c
Fixes #213 
Set, reset or query the current state with: debug [input][X] [on|off|?]
where: 'X' is 1, 2 or unspecified (all channels)
on=enable, off=disable, ?=query current state, else toggle debug state.
NB: if the compiler/linker does not fold identical constant strings, setting of output of the debug state should probably be refactored, which would tidy up the #ifdef mess a little.
=> Make the debug command be more deterministic about debug state.

platforms/atlys.py
The Spartan 6 has a number of IO banks. Each IO bank is supplied by a voltage rail which sets the supported IO standards on that bank. Let's use this fact to make configuration easier!
As well, on the Atlys, the VCCB2 rail which supplies Bank 2 is user controllable via the JP12 jumper. This means that the IO standards used change depending on that value.
Also fix the VCCAUX value, which is actually 3V3 on the Atlys. (See [Sheet 10 - FPGA POWER](https://reference.digilentinc.com/_media/atlys:atlys:atlys_sch.pdf))
=> Rework IO standards for Atlys board

Makefile
* Generate the date stamp once and reuse it.
* Add hour/minute/second to the log file.
* Tee should be appending.
* Reduce duplication of log file name.
=> Small fixes to the output logging.

gateware/hdmi_out/__init__.py, gateware/hdmi_out/phy.py, platforms/atlys.py, platforms/opsis.py, targets/atlys_base.py, targets/atlys_hdmi2eth.py, targets/atlys_hdmi2usb.py, targets/atlys_video.py, targets/common.py, targets/minispartan6_video.py, targets/opsis_base.py, targets/opsis_hdmi2usb.py, targets/opsis_video.py, targets/pipistrello_base.py
Fixes #210.
This pull request make a bunch of changes to improve the code around PLL and timing constraints. 
These are;
* Better naming of the clock signals.
* Adding a `class` for the frequency to make it easier to understand.
* Improving the documentation around the CRG module and PLL configuration. 
* Asserting the PLL configuration is as requested.
* Improving the timing constraint names and making them easier to understand.
=> Fixing the timing propagation through PLL/DCM parts in ISE.

targets/atlys_base.py
Fixes #289.
This seems to have been an accident in
https://github.com/timvideos/HDMI2USB-misoc-firmware/commit/075107405196f9fa3158e9da8a0ca7d54641286c#diff-2b70f9cc5d7a3571d43b4c7a4fc67fa6R225
=> targets/atlys: Revert to using BaseSoC rather than MiniSoC.

.travis/run.sh
* Fixes the echoing of the version information in the travis output (The actual version info moved into the version_data.c file in https://github.com/timvideos/HDMI2USB-misoc-firmware/pull/271).
* Fix  #206 - The "-dirty" status of liteEth/liteUSB in the version output
* Prevent the build from passing if the version is dirty.
=> Fix couple of version related bugs

.gitmodules
git clone `git://anongit.freedesktop.org/xorg/app/edid-decode` does not work under proxy.
It gives the error :
``fatal: unable to connect to anongit.freedesktop.org:
anongit.freedesktop.org[0: 131.252.210.161]: errno=Connection refused
anongit.freedesktop.org[1: 2610:10:20:722:a800:ff:fe24:61cf]: errno=Network is unreachable``
[.... Given that my system proxy is set properly ....]
Instead replacing it with `git clone https://anongit.freedesktop.org/git/xorg/app/edid-decode` will help everywhere without disturbing the functionality.
=> Fixed cloning edid-decode behind a proxy

firmware/framebuffer.h, firmware/hdmi_in0.c, firmware/hdmi_in0.h, firmware/hdmi_in1.c, firmware/hdmi_in1.h, firmware/heartbeat.c, firmware/heartbeat.h, firmware/processor.c, scripts/download-env.sh
The framebuffers belong to the sources not the sinks. So, simply write the heartbeat to the current framebuffer of each source.
This gets heartbeat working on non-pattern inputs again.
While we're here, set the right PATH for fxload on Debian, and remove an unnecessary volatile (part of #267).
=> Apply heartbeat to input FBs

.travis/build.sh
It looks like our prebuilt builds have been missing the flashable image since 760?
=> The flashable image is now called image*.bin

firmware/ci.c
Only one of these will be active, and output anything, so let's just run both, under the hood.
=> Replace debug (pll|mmcm) with debug clocks

scripts/build-qemu.sh, scripts/download-env.sh, scripts/enter-env.sh
Fix some of the issues I found while trying to run the linux image on qemu.
Specifically:
- Disable warnings as errors when compiling qemu
- Complain to the user if the path to the repository is known to break (contains either whitespace or ':')
- Make the download-env script continue to attempt to install conda if a previous attempt failed
=> Fix issues found while trying to run download-env

.travis/build.sh, .travis/setup.sh, scripts/download-env.sh
Current theory is that the machines are running out of disk, see https://travis-ci.org/timvideos/HDMI2USB-litex-firmware/jobs/297702973
```
error: unable to write file archive/pycon2016/v0.0.2-82-g6bdf86a/opsis/hdmi2usb/sha256sum.txt
error: unable to write file archive/pycon2016/v0.0.2-82-g6bdf86a/opsis/video/opsis_video-customvideomixersoc-opsis.bin
error: unable to write file archive/pycon2016/v0.0.2-82-g6bdf86a/opsis/video/opsis_video-customvideomixersoc-opsis.bit
error: unable to write file archive/pycon2016/v0.0.2-82-g6bdf86a/opsis/video/output.log
error: unable to write file archive/pycon2016/v0.0.2-82-g6bdf86a/opsis/video/sha256sum.txt
error: unable to write file archive/pycon2016/v0.0.2-82-g6bdf86a/pipistrello/base/output.log
error: unable to write file …
```
=> Trying to fix failing builds on Travis.

.travis/build.sh
* Fix the unstable link.
* Save more of the gateware stuff (better logs on Vivado based builds).
* Preemptive saving of micropython + linux saving.
=> travis: Improving the prebuilt stuff

.travis.yml, Makefile, scripts/build-micropython.sh, scripts/build-qemu.sh
This should make everything work if `-j` is given to make. It should also mean that the correct number of processors are used in the `./scripts/build-xxx.sh` files.
=> Better parallel make support

.gitignore, firmware/framebuffer.h, firmware/hdmi_in.sh, firmware/hdmi_in0.c, firmware/hdmi_in0.h, firmware/pattern.c, firmware/pattern.h, firmware/processor.c
We accidentally started using the same framebuffers for all inputs in 92eb6f9a1333d8c9ca83a60f54f40fa15c6aaa58
=> Calculate a FRAMEBUFFERS_BASE for hdmi_inX

scripts/enter-env.sh
The ixo-usb-jtag package in Debian is a firmware-only package, without any udev rules.
=> Only the udev rules are actually a problem

scripts/build-qemu.sh
By switching to usermode networking in qemu, because of this we no longer need to set up the tap interface, nor do we need to start tftpd as root.
This change requires a fix to the netboot code in the bios (https://github.com/enjoy-digital/litex/pull/35), otherwise it will time out fetching the second block of the firmware (the second 512 bytes).
=> Make it possible to start an image in qemu as a user.

firmware/framebuffer.h
@stefanor - Welp we screwed this one up. Pattern was ending up at *zero* which was overwriting the firmware. Discovered via running in qemu and getting;
```
Telnet listening on port 23
VM paused due to illegal instruction. Connect a debugger or switch to the monitor console to find out more.
```
=> firmware: Put pattern framebuffer at FRAMEBUFFER_OFFSET and everything below that.

.travis/prevent-condarc.sh, .travis/setup.sh, scripts/download-env.sh
Conda should be self contained in the `build/conda` directory. Add travis checks for it.
=> Make conda not use a user's home directory.

firmware/mdio.c
We have a separate command for that.
=> Don't do mdio_dump in mdio_status

platforms/opsis.py
which are actually present on the pcb as .1" headers
=> gateware opsis: declare debug_io0/1

getting-started.md
I'm not sure about "make load-fx2" or "make view" (these aren't valid make targets either).
Also, to get things to upload, I found I had to do a "make firmware-load", then type in "serialboot". I don't know if this is a requirement, or I was stuffing something up.
=> Correct getting-started.md 's make commands

firmware/version_data.py
=> Python script of version_data

firmware/ci.c
the `help` command currently does not show the `version` option. This adds it to the initial section
=> Add version to help prompt

README.md
The crowd-funding page no longer allows purchasing of Opsis boards, so link to the supplier page
=> Link to current Opsis supplier page

doc/notes.md
`XILINX_DIR` must be set before entering the environment if Xilinx is installed to a non-default location
=> Add XILINX_DIR notes

targets/cmod_a7/Makefile.mk
Changed default target from `net` to `base`.
=> cmod_a7: Fixing default target.

.travis.yml
```
Running apt-get update by default has been disabled.
You can opt into running apt-get update by setting this in your .travis.yml file:
addons:
apt:
update: true
```
=> travis: Adding update as travis suggested.

firmware/ci.c
I think #418 can be resolved by the following commit.
=> Improve `debug edid` help and error

targets/nexys_video/base.py
=> targets/nexys_video: Fix for upstream change in UART interface

.travis.yml, targets/arty/base.py, targets/arty/net.py, targets/atlys/base.py, targets/atlys/net.py, targets/basys3/base.py, targets/cmod_a7/base.py, targets/galatea/base.py, targets/mimasv2/base.py, targets/minispartan6/base.py, targets/neso/base.py, targets/netv2/base.py, targets/nexys_video/base.py, targets/nexys_video/net.py, targets/opsis/base.py, targets/opsis/net.py, targets/pipistrello/base.py, targets/saturn/base.py, targets/sim/base.py, targets/sim/net.py, targets/waxwing/base.py
* Move everything to kwargs style for `integrated_rom_size` and
`integrated_sram_size` values.
* Override the `intergrated_rom_size` when using Ethernet and or1k.
=> targets: Working on ROM size fixes.

.travis.yml
The Xilinx toolchain has been fixed so these builds no longer fail. \o/
Fixes https://github.com/timvideos/HDMI2USB-litex-firmware/issues/455
=> travis: These builds no longer fail.

firmware/processor.c
Previously, the resulting pixel clock was 1/10th of the actual value. This PR fixes the calculation. Also added a warning in case the VCO frequency goes outside the allowed range.
The HDMI output is now working in Mimas A7 with this fix.
=> firmware: fix MMCM multiplier & divisor calculation

firmware/config.c
This will help testing so I can see something working that does not rely on inputs or console.
output 0 is typically the projector, 
output 1 is confidence monitor - the presenter will see color bars until the systemd script fires and sets it to input1
=> Default Output 1 to Pattern.

firmware/edid.c, firmware/processor.c
Fix assumption that both h_sync and v_sync offset/width are 10-bit values, which resulted in the v_sync offset being sent as if it were 0; h_sync offset/width are 10-bit values, but v_sync offset/width
are 6-bit values.
`t->v_sync_offset_width_l` part of the change tested with `read-edid` in https://github.com/timvideos/HDMI2USB-litex-firmware/issues/478; `t->hv_sync_offset_width_h` part of the change only compiled.  (HackFest building logistics mean I can't test it with read-edid now, but by inspection the 4-bit/2-bit split seems more correct than the 8-bit shifts that were there before.)
`v_sync_offset` of 720p set back to recommended 5 lines value (from https://github.com/timvideos/HDMI2USB-litex-firmware/issues/478) now that it's actually being sent properly rather than as zero.
For a …
=> EDID: v_sync offset/width are 6-bit values
