firmware/lm32/ci.c, firmware/lm32/edid.c, firmware/lm32/edid.h, firmware/lm32/processor.c, firmware/lm32/processor.h
* Clean up the help printing code a little.
* Print help when errors / unknown commands are used.
* Add 720p50 mode
* Adding documentation to EDID mode table.
=> Improving the help and adding more documentation

.travis-run.sh, Makefile
=> Adding base back into Travis-CI

.travis/run.sh
* Build the hdmi2ethernet target for the atlys board.
* Slight easier to read output.
=> Small travis refactor

scripts/get-env-root.sh
It was adding root, not your current user.
=> scripts/get-env-root.sh: Fix dialout user adding

scripts/get-env-root.sh
#bash is very helpful and this is a good read.  both entertaining and useful.
!faq location; greybot: http://mywiki.wooledge.org/BashFAQ/028 -- How do I determine the location of my script?  I want to read some config files from the same place.
=> copy 52-hdmi2usb.rules from same dir script is in.

.travis/run.sh, Makefile, firmware/fx2/Makefile
Add test in travis build to see if make clean removes all the files generated by the build
=> Add test in travis to check if make clean actually removes all generated files

.travis/run.sh
Copy the firmware built by travis to HDMI2USB-firmware-prebuilt
Will need GITHUB_TOKEN set in travis and COPY_REPO_OWNER changed to not copy to my fork
HDMI2USB-firmware-prebuilt will also need tidied up like the forks
=> Copy firmware built by travis

.travis/run.sh
Minor fixes and improvements for the prebuilt images
Issues #98, #99, #100 and #101 
I will deal with #93 separately
=> Build copy fixes

scripts/README.md, scripts/flash-hdmi2usb.sh
* Now "make load-fx2" to load fx2 firmware.
* PROG is no longer needed (default openocd should work).
=> Fixing the scripts/README.md for changes

scripts/README.md
The licensing service moved for Xilinx.
=> Fix licensing URL

README.md
=> Small fixes to the converted README.

Makefile.lm32, gateware/firmware.py, targets/atlys_base.py, targets/common.py, targets/opsis_base.py, targets/pipistrello_base.py
=> Romboot fix

.gitmodules
* misoc/migen have moved to a different format, we are currently still on the
legacy version.
* We want a couple of small fixes in these repos.
=> third_party: Change misoc/migen to TimVideos versions (and update).

platforms/atlys.py, platforms/opsis.py
=> platform: Fix comments to have \r\n

firmware/lm32/fx2.c, platforms/opsis.py
=> Fix the FX2 reboot command

targets/atlys_base.py, targets/atlys_hdmi2eth.py, targets/atlys_hdmi2usb.py, targets/atlys_video.py, targets/opsis_hdmi2usb.py, targets/opsis_video.py
* Move the VideoMixerSoC into it's own file.
* Remove duplication of VideoMixerSoC in both hdmi2usb and hdmi2eth targets.
* Small formatting cleanups.
=> targets: Refactoring how the targets work.

scripts/get-env.sh, scripts/settings.sh, scripts/setup-env.sh
* Actually download the specific version we are checking for from conda.
* Move the version information to a settings.sh file.
* Small other clean up.
=> scripts: Rework version information for toolchains

.gitignore, .gitmodules, Makefile, Makefile.lm32, platforms/atlys.py, targets/atlys_base.py, targets/atlys_hdmi2usb.py
=> targets/atlys: Getting the SPI flash working on the Atlys board

Makefile
* Couple of small makefile changes.
* third_party/misoc bios fixes.
=> Couple of small fixes.

platforms/opsis.py, platforms/pipistrello.py, targets/opsis_base.py, targets/pipistrello_base.py
=> Adding support for SPI flash on Pipistrello and Opsis board.

.gitignore, firmware/lm32/Makefile, firmware/lm32/version.c, firmware/lm32/version_data.sh
* Include board/target in firmware info.
* Put the data in an .c file
* Check the correct defines are in use.
=> Improve the version data information.

firmware/lm32/ci.c, gateware/cas.py, platforms/atlys.py, targets/atlys_base.py, targets/atlys_hdmi2eth.py, targets/atlys_hdmi2usb.py
=> Adding a module to allow firmware access to the LEDs, Push Buttons and Switches (on the Atlys)

firmware/lm32/ci.c, firmware/lm32/hdmi_in0.c, firmware/lm32/hdmi_in1.c, gateware/freq_count.py, gateware/hdmi_in/__init__.py, targets/opsis_base.py, targets/opsis_video.py
Add frequency counter gateware (finally! :P). Check the master branch, minispartan_{base, video}.py for example usage.
=> Frequency Counter for Debugging

Makefile, scripts/download-prebuilt.sh
In theory, it will download the latest git revision in your branch which
is upstream.
Fixes #322.
=> Fix the download-prebuilt script.

.travis/setup.sh
* edid-decode changed from cb0ee55 to 60a6787
* flash_proxies changed from d2ab903 to 171a890
* litedram changed from 47755e5 to f31f8a0
* liteeth changed from c43fb26 to 48fb464
* litepcie changed from 6a69b46 to c836c46
* litescope changed from 8d87992 to d4d63d7
* litevideo changed from f628a61 to 8caa1fd
* litex changed from f25e46c4 to e42ab27f
Full submodule status
--
60a67872f213fda03df4968ca61d2eb17a8cb8a8 edid-decode (remotes/origin/HEAD)
171a890fa5526c6a2dca8b925f2806c4abef4c72 flash_proxies (remotes/origin/HEAD)
f31f8a03ff6911befa6d07bf347f8478c30448d8 litedram (heads/master)
48fb4647bdb3e3a1766dec7b96fefe872c79e8a6 liteeth (remotes/origin/HEAD)
c836c467b8d086c7ade23a45557644e4620a4bdc litepcie (remotes/origin/HEAD)
1b09801f06f06224de68fdc9c0e7297948d59569 litesata …
=> Updating submodules.

gateware/cas.py
Generated header now includes constant for number of devices
=> Added constants to cas module

.travis.yml, .travis/add-local-submodule.sh, .travis/build.sh, .travis/setup.sh
* Enabling failing pipistrello build
* Pull submodules from a person.
* Fixing commit messages.
* Cat the log file on failure.
=> Improving Travis scripts.

targets/arty/net.py, targets/atlys/net.py, targets/atlys/video.py, targets/nexys_video/base.py, targets/nexys_video/net.py, targets/nexys_video/video.py, targets/opsis/base.py, targets/opsis/video.py
This is needed for Linux on LiteX.
Pull reqest https://github.com/enjoy-digital/litex/pull/34 must be merged first.
=> LiteX uart is moving to IRQ 2

.travis.yml, targets/pipistrello/base.py
This pull request fixes the build for the pipistrello board.
=> Fixing Pipistrello board

Makefile, scripts/build-qemu.sh
These are not really related, but they were sitting in my repo when I started to update to latest upstream.  I figured I clean them up and send upstream.
=> Support in.tftpd and gdb debugging in qemu

firmware/ci.c, platforms/netv2.py, platforms/nexys_video.py, targets/atlys/video.py, targets/netv2/video.py, targets/nexys_video/video.py, targets/opsis/video.py
=> Fix the HDMI info reporting

.travis/build.sh, .travis/download-prebuilt.sh, .travis/fixup-git.sh, .travis/push-prebuilt.sh
This significantly reduces the amount of disk space needed on the travis host.
=> Change the prebuilt stuff to use subversion

firmware/hdmi_in.sh
=> Fixes dvisampler1 displaying as dvisampler0

scripts/download-env.sh, scripts/enter-env.sh
=> scripts: Move to Python 3.6

.travis/generate-prebuilt-list.py
Allow extra columns to be added to the spreadsheet.
=> travis: Fixing generate-prebuilt-list

scripts/download-env.sh, scripts/enter-env.sh
Otherwise it breaks the SAVE code in .travis/build.sh
https://github.com/timvideos/HDMI2USB-litex-firmware/blob/master/.travis/build.sh#L223-L236
=> scripts: Restore the nullglob setting.

getting-started.md
Addition in Step 4)  Loading temporarily
$make gateware-load
$make firmware-load
BIOS>serialboot
$make firmware-connect
=> Change in  getting-started.md

.travis.yml
Currently there are lots of failures which is preventing the HDMI2USB
targets from getting built. For now disable the multi-stage builds.
=> travis: Make everything the same build stage.

.travis.yml, platforms/mimas_a7.py, targets/mimas_a7/Makefile.mk, targets/mimas_a7/base.py, targets/mimas_a7/bridge_net.py, targets/mimas_a7/net.py, targets/mimas_a7/video.py
Support for the [Numato Mimas A7 board](https://numato.com/product/mimas-a7-artix-7-fpga-development-board-with-ddr-sdram-and-gigabit-ethernet).
=> Support for Mimas A7

.travis.yml
* Get rid of the build stages.
* Line everything up better.
=> Refactor the `.travis.yml` file a little

firmware/Makefile, firmware/ci.c, firmware/hdmi_in.sh, firmware/hdmi_in0.c
untested, but I think building is broken.  so here it is.
=> Pattern closes #474

firmware/ci.c
=> move #endif - fixes #479
